spring:
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 2333

#下面是自定义设置
mysql:
  host: 101.126.90.250
  database: creeperhub
  port: 3306
  username: WJZ
  password: 123456

redis:
  host: 101.126.90.250
  port: 6379
  password: 123456